version: '3.8'

services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
  backend:
    build: backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/src:/app/src